# Generated by Django 5.2.12 on 2026-04-06 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('rows_json', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('pdf_name', models.CharField(blank=True, default='', max_length=255)),
                ('xlsx_name', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
