# Generated by Django 5.2.12 on 2026-04-07 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0002_invoicejob_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicejob',
            name='contractor_abn',
            field=models.CharField(default='14 357 358 253', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='contractor_name',
            field=models.CharField(default='Rajath Thaliyadath', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='employer_abn',
            field=models.CharField(default='98 665 950 201', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='employer_name',
            field=models.CharField(default='ParcelRun PTY LTD', max_length=255),
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(default='ParcelRun PTY LTD', max_length=255)),
                ('employer_abn', models.CharField(default='98 665 950 201', max_length=64)),
                ('contractor_name', models.CharField(default='Rajath Thaliyadath', max_length=255)),
                ('contractor_abn', models.CharField(default='14 357 358 253', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
