# Generated by Django 5.2.12 on 2026-04-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0003_invoicejob_contractor_abn_invoicejob_contractor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='account_name',
            field=models.CharField(default='Rajath Thaliyadath', max_length=255),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='account_number',
            field=models.CharField(default='1179 6764', max_length=64),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='bank_name',
            field=models.CharField(default='Commonwealth Bank Macquarie Centre North Ryde', max_length=255),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='bsb_number',
            field=models.CharField(default='062320', max_length=64),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='rate_per_parcel',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='account_name',
            field=models.CharField(default='Rajath Thaliyadath', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='account_number',
            field=models.CharField(default='1179 6764', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='bank_name',
            field=models.CharField(default='Commonwealth Bank Macquarie Centre North Ryde', max_length=255),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='bsb_number',
            field=models.CharField(default='062320', max_length=64),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='rate_per_parcel',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
        ),
    ]
