# Generated by Django 5.2.12 on 2026-04-07 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicer', '0004_accountprofile_account_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='map_account_name_cell',
            field=models.CharField(default='C31', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_account_number_cell',
            field=models.CharField(default='C30', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_bank_name_cell',
            field=models.CharField(default='C28', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_bsb_cell',
            field=models.CharField(default='C29', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_contractor_abn_cell',
            field=models.CharField(default='G9', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_contractor_name_cell',
            field=models.CharField(default='G8', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_contractor_name_line_cell',
            field=models.CharField(default='B25', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_data_first_row',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_data_last_row',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_date_cell',
            field=models.CharField(default='B24', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_employer_abn_cell',
            field=models.CharField(default='C9', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_employer_name_cell',
            field=models.CharField(default='C8', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_invoice_number_cell',
            field=models.CharField(default='G3', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_rate_cell',
            field=models.CharField(default='G12', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_sum_row',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_table_header_row',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='map_total_label_cell',
            field=models.CharField(default='B21', max_length=16),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='use_custom_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='save_weekly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SavedInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_monday', models.DateField()),
                ('pdf_name', models.CharField(max_length=255)),
                ('xlsx_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_record', to='invoicer.invoicejob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
